"""
tampering_detector.py — Detects alterations to Etendo core files.

Compares SHA-256 checksums of the current installation against a clean
manifest generated by etendo_generate_manifest.py.
"""

import hashlib
import json
import os
from pathlib import Path


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_manifest(manifest_path: str) -> dict:
    with open(manifest_path, "r") as f:
        return json.load(f)


def detect_tampering(etendo_root: str, manifest_path: str) -> dict:
    """
    Compares the current installation against a clean manifest.

    Returns:
      {
        "modified": [{"path": "...", "expected": "...", "actual": "..."}],
        "missing":  ["path/to/missing/file"],
        "extra":    ["path/to/extra/file"],
        "total_checked": int,
        "tampering_score": float  # 0.0 = clean, 1.0 = fully altered
      }
    """
    manifest = load_manifest(manifest_path)
    clean_files = manifest.get("files", {})  # {relative_path: sha256}

    modified = []
    missing = []

    for rel_path, expected_hash in clean_files.items():
        abs_path = os.path.join(etendo_root, rel_path)
        if not os.path.exists(abs_path):
            missing.append(rel_path)
            continue
        actual_hash = sha256_file(abs_path)
        if actual_hash != expected_hash:
            modified.append({
                "path": rel_path,
                "expected": expected_hash,
                "actual": actual_hash,
            })

    total = len(clean_files)
    altered = len(modified) + len(missing)
    score = round(altered / total, 4) if total > 0 else 0.0

    return {
        "modified": modified,
        "missing": missing,
        "total_checked": total,
        "tampering_score": score,
    }


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage: tampering_detector.py <etendo_root> <manifest.json>")
        raise SystemExit(1)

    result = detect_tampering(sys.argv[1], sys.argv[2])
    print(json.dumps(result, indent=2))
